### ISSUE TITLE
Add lint etc. workflows and hooks for cleaning the code

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/qgis_plugin_tools#6]
- Black
- Pylint
- Pep8

TBA

**Comment by Joonalai** [comment]
@LKajan do you have any preferences about tools used?

**Comment by LKajan** [comment]
Here's my picks
[flake8](https://flake8.pycqa.org/en/latest/index.html) for linting
[pep8-naming](https://pypi.org/project/pep8-naming/) flake8-plugin for checking variable name conventions
[flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) flake8-plugin for common design problems
[isort](https://github.com/PyCQA/isort) for autosorting imports
[black](https://github.com/psf/black) for formatting
[pre-commit](https://github.com/pre-commit/pre-commit) for checking all above before committing changes

**Comment by Joonalai** [comment]
@LKajan do you have any good .flake8 etc. files that could be added to the template?
